name: Upload AWS Control Statuses to ServiceNow

on:
  schedule:
    - cron: '0 14 * * 5'   # every week
  workflow_dispatch:     # manual trigger optional

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SN_I: ${{ secrets.SN_I }}
      SN_T: ${{ secrets.SN_T }}
      SN_U: ${{ secrets.SN_U }}
      SN_P: ${{ secrets.SN_P }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run sync script
        run:
          python main.py